CC=     gcc
CFLAGS= -Wall -ansi -pipe -O3
SRC=    sick.c util.c sick_poster.c
OBJ=    $(SRC:.c=.o)
AR=     ar
RANLIB= ranlib

all: tsick

tsick: tsick.o libsick.a
	$(CC) $(CFLAGS) -o tsick tsick.o libsick.a

libsick.a: $(OBJ)
	$(AR) r $@ $?
	$(RANLIB) libsick.a

clean:
	- rm libsick.a tsick.o tsick $(OBJ)
